# Generated by Django 5.1.6 on 2025-02-12 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='source_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange', to='currency.currency'),
        ),
    ]
